# async-v2.0.3:
#   url: https://github.com/socketry/async
#   command: bundle exec rspec
#   branch: v2.0.3
# async-v2.1.0:
#   url: https://github.com/socketry/async
#   command: bundle exec rspec
#   branch: v2.1.0
async:
  url: https://github.com/socketry/async
  command: bundle exec sus
async-io:
  url: https://github.com/socketry/async-io
  command: bundle exec rspec
async-http:
  url: https://github.com/socketry/async-http
  command: bundle exec rspec
